<a href="https://colab.research.google.com/github/ali1810/Big-DATA-week1-/blob/master/pubchem_sol_data_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Import the required library 
import requests
from bs4 import BeautifulSoup
import re

In [ ]:
##install pubchem python library
!pip install pubchempy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pubchempy
  Downloading PubChemPy-1.0.4.tar.gz (29 kB)
Building wheels for collected packages: pubchempy
  Building wheel for pubchempy (setup.py) ... done
  Created wheel for pubchempy: filename=PubChemPy-1.0.4-py3-none-any.whl size=13834 sha256=50beadcc6ce2d1e4f260b2d17412d524392e80d08ffb9d11dfb634ac68a04770
  Stored in directory: /root/.cache/pip/wheels/7c/3d/8c/8192697412e9899dc55bbbb08bbc1197bef333caaa2a71c448
Successfully built pubchempy
Installing collected packages: pubchempy
Successfully installed pubchempy-1.0.4

In [ ]:
## Get the SMILES WITH COMPOUND NAME
data = requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/aspirin/xml")
html = BeautifulSoup(data.content, "xml")
html.find_all("PC-Urn_label")
smiles_tag = html.find(name="PC-Urn_label", string="SMILES")
smiles_parents = smiles_tag.find_parent("PC-InfoData")
smiles = smiles_parents.find('PC-InfoData_value_sval').string
smiles

'CC(=O)OC1=CC=CC=C1C(=O)O'

In [ ]:
img=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244/PNG?record_type=3d&image_size=small")

In [ ]:
img=requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244/PNG")

NameError: ignored

In [ ]:
# 2 Fisrt to get the CID from SMILES 
prop=pcp.get_properties([ 'MolecularWeight'], 'CC(=O)OC1=CC=CC=C1C(=O)O', 'smiles')

In [ ]:
print(prop)

[{'CID': 2244, 'MolecularWeight': '180.16'}]

In [ ]:
x = list(map(lambda x: x["CID"], prop))
print(x)
y=x[0]
print(y)

[2244]
2244

In [ ]:
a = "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml?heading=Solubility"
print(a)
z=(a%y)
print(z)
data=requests.get(a%y)
print(data)

https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml?heading=Solubility
https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/2244/xml?heading=Solubility
<Response [200]>

In [ ]:
prop=pcp.get_properties([ 'MolecularWeight'], SMILES, 'smiles')
   x = list(map(lambda x: x["CID"], prop))
   y=x[0]
   #print(y)
   x = "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml?heading=Solubility"
   data=requests.get(x % y)
   html = BeautifulSoup(data.content, "xml")
   solubility = html.find_all('String')
   #print(dtype(solubility))
   if solubility == None:
      return None  
   #elif          # or pass
   else:
     #solub=html.find_all('String')
     return solubility

In [ ]:
print(type(img))

<class 'requests.models.Response'>

In [ ]:
from google.colab.patches import cv2_imshow
import cv2
#img = cv2.imread('logo.png', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

AttributeError: ignored

In [ ]:
import pubchempy as pcp
import requests
from bs4 import BeautifulSoup
### Function to get solubility data from Pubchem 
def smiles_to_sol_new(SMILES):
   prop=pcp.get_properties([ 'MolecularWeight'], SMILES, 'smiles')
   x = list(map(lambda x: x["CID"], prop))
   y=x[0]
   #print(y)
   x = "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml?heading=Solubility"
   data=requests.get(x % y)
   html = BeautifulSoup(data.content, "xml")
   solubility = html.find_all('String')
   #print(dtype(solubility))
   if solubility == None:
      return None  
   #elif          # or pass
   else:
     #solub=html.find_all('String')
     return solubility

In [ ]:
smiles = input("Enter your smiles : ")

## passing smiles to a function to get the solubility from Pubchem websites 
smiles_to_sol_new(smiles)

Enter your smiles : CC(=O)OC1=CC=CC=C1C(=O)O

[<String>less than 1 mg/mL at 73° F (NTP, 1992)</String>,
 <String>0.03 M</String>,
 <String>1 g sol in: 300 mL water at 25 °C, 100 mL water at 37 °C, 5 mL alcohol, 17 mL chloroform, 10-15 mL ether; less sol in anhydrous ether</String>,
 <String>In water, 4,600 mg/L at 25 °C</String>,
 <String>Solubility in water, g/100ml at 15 °C: 0.25 (poor)</String>,
 <String>(77°F): 0.3%</String>]

In [ ]:
data = requests.get("https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/2244/xml?heading=Solubility")

In [ ]:
html = BeautifulSoup(data.content, "xml")

In [ ]:
df=html.find_all('String')

In [ ]:
df

[<String>less than 1 mg/mL at 73° F (NTP, 1992)</String>,
 <String>0.03 M</String>,
 <String>1 g sol in: 300 mL water at 25 °C, 100 mL water at 37 °C, 5 mL alcohol, 17 mL chloroform, 10-15 mL ether; less sol in anhydrous ether</String>,
 <String>In water, 4,600 mg/L at 25 °C</String>,
 <String>Solubility in water, g/100ml at 15 °C: 0.25 (poor)</String>,
 <String>(77°F): 0.3%</String>]

In [ ]:
##install pubchem python library
!pip install pubchempy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pubchempy
  Downloading PubChemPy-1.0.4.tar.gz (29 kB)
Building wheels for collected packages: pubchempy
  Building wheel for pubchempy (setup.py) ... done
  Created wheel for pubchempy: filename=PubChemPy-1.0.4-py3-none-any.whl size=13834 sha256=959ae932d64832f1639eb78845e2f57e70da1c920de95cd3df11850ee3bc2f28
  Stored in directory: /root/.cache/pip/wheels/7c/3d/8c/8192697412e9899dc55bbbb08bbc1197bef333caaa2a71c448
Successfully built pubchempy
Installing collected packages: pubchempy
Successfully installed pubchempy-1.0.4

In [ ]:
import pubchempy as pcp

import pandas as pd

In [ ]:
prop=pcp.get_properties([ 'MolecularWeight' 
],'C1=CC=C(C=C1)C=O', 'smiles')

In [ ]:
import pubchempy as pcp
import requests
from bs4 import BeautifulSoup
### Function to get solubility data from Pubchem 
def smiles_to_sol(SMILES):
   prop=pcp.get_properties([ 'MolecularWeight'], SMILES, 'smiles')
   x = list(map(lambda x: x["CID"], prop))
   y=x[0]
   #print(y)
   x = "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml"
   data=requests.get(x % y)
   html = BeautifulSoup(data.content, "xml")
   solubility = html.find(name='TOCHeading', string='Solubility')
   #solubility = html.find_all('String')
   #print(dtype(solubility))
   if solubility == None:
      return None  
   #elif          # or pass
   else:
     solub=solubility.find_next_sibling('Information').find(name='String').string
     return solub

In [ ]:
smiles = input("Enter your smiles : ")

## passing smiles to a function to get the solubility from Pubchem websites 
smiles_to_sol(smiles)

Enter your smiles : CC(=O)OC1=CC=CC=C1C(=O)O

'less than 1 mg/mL at 73° F (NTP, 1992)'

In [ ]:
prop=pcp.get_properties([ 'MolecularWeight'], 'CC(=O)OC1=CC=CC=C1C(=O)O','smiles')
x = list(map(lambda x: x["CID"], prop))
y=x[0]
   #print(y)
x = "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view/data/compound/%s/xml"
data=requests.get(x % y)
html = BeautifulSoup(data.content, "xml")
solubility = html.find(name='TOCHeading', string='Solubility')#,div='section-content-item')
print(solubility)

<TOCHeading>Solubility</TOCHeading>

In [ ]:

## Taking smiles from user 
smiles = input("Enter your smiles : ")

## passing smiles to a function to get the solubility from Pubchem websites 
smiles_to_sol(smiles)

Enter your smiles : CC(=O)OC1=CC=CC=C1C(=O)O

AttributeError: ignored

In [ ]:
import pandas as pd
### Getting the list of the smiles 



#df=pd.read_excel("/content/drive/MyDrive/pubchem_1_5000.xlsx")
df=pd.read_csv("/content/drive/MyDrive/CID-SMILES.csv")




df

In [ ]:
m=4.6/180
m

0.025555555555555554

In [ ]:
ml=10**(-1.60)
ml

0.025118864315095794

In [ ]:
print(len(df))

5000

In [ ]:

P_sol=[]
for i in range(len(df)-4950):
  try:
    sol=smiles_to_sol_new(df.SMILES[i])
    P_sol.append(sol)
  except AttributeError as e:
    sol=='No string'
    P_sol.append(sol)

   # P_sol.append(sol)

In [ ]:
print(len(P_sol))

50

In [ ]:
print(P_sol)

[[], [], [], [<String>greater than or equal to 100 mg/mL at 67.6° F (NTP, 1992)</String>, <String>13.31 M</String>, <String>SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ACETONE, BENZENE, CARBON TETRACHLORIDE.</String>, <String>Solubility in water: soluble</String>, <String>Soluble in water</String>, <String>Soluble (in ethanol)</String>], [], [<String>13.8 [ug/mL]</String>, <String>Soluble in ether, benzene, and carbon disulfide; sparingly soluble in cold, freely soluble in hot alcohol</String>, <String>In water, 9.24 mg/L at 25 °C</String>, <String>Solubility in water at 15 °C: very poor</String>], [], [], [], [<String>5 to 10 mg/mL at 66° F (NTP, 1992)</String>, <String>0.09 M</String>, <String>In water, 8,600 mg/L at 25 °C</String>, <String>Solubility in water at 20 °C: 0.86% wt</String>, <String>0.869 g/100 mL water at 20 °C</String>, <String>Miscible with alcohol, chloroform, ether</String>, <String>For more Solubility (Complete) data for 1,2-Dichloroethane (6 total), please visit the HSDB record page.</String>, <String>8.6 mg/mL at 25 °C</String>, <String>Solubility in water, g/100ml: 0.87</String>, <String>0.9%</String>], [], [<String>less than 1 mg/mL at 70° F (NTP, 1992)</String>, <String>2.70e-04 M</String>, <String>Sparingly soluble in alcohol. Miscible with ether, benzene, petroleum ether, carbon disulfide</String>, <String>In water, 49.0 mg/L at 25 °C</String>, <String>Solubility in water, mg/l: 34.6</String>, <String>0.003%</String>], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [<String>greater than or equal to 100 mg/mL at 66° F (NTP, 1992)</String>, <String>In water, 1.11X10+5 mg/L at 25 °C (est)</String>, <String>Miscible in all proportions with water</String>, <String>Soluble in ether</String>, <String>Soluble in acetone and methanol</String>, <String>Solubility in water: miscible</String>, <String>Miscible</String>]]

In [ ]:
df2 = pd.DataFrame(P_sol)

In [ ]:
df3=df2.loc[:,2:2]

In [ ]:
df3

                                                    2
0                                                None
1                                                None
2                                                None
3   [SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ...
4                                                None
5                      [In water, 9.24 mg/L at 25 °C]
6                                                None
7                                                None
8                                                None
9                     [In water, 8,600 mg/L at 25 °C]
10                                               None
11  [Sparingly soluble in alcohol. Miscible with e...
12                                               None
13                                               None
14                                               None
15                                               None
16                                               None
17                                               None
18                                               None
19                                               None
20                                               None
21                                               None
22                                               None
23                                               None
24                                               None
25                                               None
26                                               None
27                                               None
28                                               None
29           [Miscible in all proportions with water]
30  [SOL IN ALL PROPORTIONS IN WATER, ALC, ORG SOL...
31                                               None
32                                               None
33                                               None
34                                               None
35                                               None
36                                               None
37                                               None
38                                               None
39                                               None
40                                               None
41                                               None
42                                               None
43                             [Soluble (in ethanol)]
44                                               None
45                                               None
46                                               None
47                                               None
48                                               None
49                                               None

In [ ]:
df4=df3.dropna() 

df4

,2,3
3,"[SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ...",[Solubility in water: soluble]
5,"[In water, 9.24 mg/L at 25 °C]",[Solubility in water at 15 °C: very poor]
9,"[In water, 8,600 mg/L at 25 °C]",[Solubility in water at 20 °C: 0.86% wt]
11,[Sparingly soluble in alcohol. Miscible with e...,"[In water, 49.0 mg/L at 25 °C]"
29,[Miscible in all proportions with water],[Soluble in ether]

In [ ]:
df1.loc[:,1:3]

,1,2,3
0,None,None,None
1,None,None,None
2,None,None,None
3,[13.31 M],"[SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ...",[Solubility in water: soluble]
4,None,None,None
5,"[Soluble in ether, benzene, and carbon disulfi...","[In water, 9.24 mg/L at 25 °C]",[Solubility in water at 15 °C: very poor]
6,None,None,None
7,None,None,None
8,None,None,None
9,[0.09 M],"[In water, 8,600 mg/L at 25 °C]",[Solubility in water at 20 °C: 0.86% wt]
10,None,None,None
11,[2.70e-04 M],[Sparingly soluble in alcohol. Miscible with e...,"[In water, 49.0 mg/L at 25 °C]"
12,None,None,None
13,None,None,None
14,None,None,None
15,None,None,None
16,None,None,None
17,None,None,None
18,None,None,None
19,None,None,None
20,None,None,None
21,None,None,None
22,None,None,None
23,None,None,None
24,None,None,None
25,None,None,None
26,None,None,None
27,None,None,None
28,None,None,None
29,"[In water, 1.11X10+5 mg/L at 25 °C (est)]",[Miscible in all proportions with water],[Soluble in ether]

In [ ]:
### Making dataframe withb solubility  dataset 
#df1 = pd.DataFrame(P_sol)
df3.columns =['Solubility']
print(df3)

                                           Solubility
0                                                None
1                                                None
2                                                None
3   [SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ...
4                                                None
5                      [In water, 9.24 mg/L at 25 °C]
6                                                None
7                                                None
8                                                None
9                     [In water, 8,600 mg/L at 25 °C]
10                                               None
11  [Sparingly soluble in alcohol. Miscible with e...
12                                               None
13                                               None
14                                               None
15                                               None
16                                               None
17                                               None
18                                               None
19                                               None
20                                               None
21                                               None
22                                               None
23                                               None
24                                               None
25                                               None
26                                               None
27                                               None
28                                               None
29           [Miscible in all proportions with water]
30  [SOL IN ALL PROPORTIONS IN WATER, ALC, ORG SOL...
31                                               None
32                                               None
33                                               None
34                                               None
35                                               None
36                                               None
37                                               None
38                                               None
39                                               None
40                                               None
41                                               None
42                                               None
43                             [Soluble (in ethanol)]
44                                               None
45                                               None
46                                               None
47                                               None
48                                               None
49                                               None

In [ ]:
### merging the data in one dataframe with smiles and solubility 

df_new = pd.concat([df[0:50], df3], axis=1)
df_new

,SrN,SMILES,Solubility
0,1,CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C,None
1,2,CC(=O)OC(CC(=O)O)C[N+](C)(C)C,None
2,3,C1=CC(C(C(=C1)C(=O)O)O)O,None
3,4,CC(CN)O,"[SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ..."
4,5,C(C(=O)COP(=O)(O)O)N,None
5,6,C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl,"[In water, 9.24 mg/L at 25 °C]"
6,7,CCN1C=NC2=C(N=CN=C21)N,None
7,8,CCC(C)(C(C(=O)O)O)O,None
8,9,C1(C(C(C(C(C1O)O)OP(=O)(O)O)O)O)O,None
9,11,C(CCl)Cl,"[In water, 8,600 mg/L at 25 °C]"
10,12,C1=C(C=C(C(=C1O)O)O)O,None
11,13,C1=CC(=C(C=C1Cl)Cl)Cl,[Sparingly soluble in alcohol. Miscible with e...
12,14,CCCCCC(=O)C=CC1C(CC(=O)C1CCCCCCC(=O)O)O,None
13,15,CC12CCC(=O)CC1CCC3C2CCC4(C3CCC4O)C,None
14,16,C1CCC(=O)NCCCCCC(=O)NCC1,None
15,17,C1C=CC(=NC1C(=O)O)C(=O)O,None
16,18,C(C(C(C(=O)C(=O)C(=O)O)O)O)O,None
17,19,C1=CC(=C(C(=C1)O)O)C(=O)O,None
18,20,C1=CC(=C(C(=C1)O)O)CCC(=O)O,None
19,21,CCC(C(=O)C)(C(=O)O)O,None
20,22,CC(=O)C(C)(C(=O)O)O,None
21,23,C(=CC(=C(C(=O)O)N)C(=O)O)C=O,None
22,24,C(C(C(C1(C(N(C2C(N1O)C(=O)NC(=N2)N)O)O)O)O)O)O,None
23,26,CC(=O)C(=O)C1=NC2C(N=C(NC2=O)N)N(C1O)O,None
24,28,C(=CC(=O)O)C=C(C(=O)O)N,None
25,29,C(=O)C(C(=O)O)N,None
26,30,C(=CC=O)C=C(C(=O)O)N,None
27,31,CC(CO)(C(COP(=O)(O)O)O)O,None
28,32,C(=CC(=O)O)C=C(C(=O)O)C(=O)O,None
29,33,C(C=O)Cl,[Miscible in all proportions with water]
30,34,C(CCl)O,"[SOL IN ALL PROPORTIONS IN WATER, ALC, ORG SOL..."
31,35,C1=CC(OC1=O)(CC(=O)O)Cl,None
32,36,CC(C)C(C(C(=O)O)O)C(=O)O,None
33,37,C(C(C(CO)O)O)C(=O)C(=O)O,None
34,38,CC(C)(CO)C(=O)C(=O)O,None
35,39,CC1(COC(=O)C1=O)C,None
36,40,C1C(C(C(OC1O)CO)O)O,None
37,41,CSCCC(=O)C(=COP(=O)(O)O)O,None
38,42,C(CC(=O)O)C(=O)C=CC=C(C(=O)O)O,None
39,43,C(CC(=O)O)C(C(=O)O)O,None
40,44,C(C(=O)[O-])(C(=O)[O-])O,None
41,45,C(C(=O)O)(C(=O)O)O,None
42,46,C(C(C(COP(=O)(O)O)O)O)C(=O)C(=O)O,None
43,47,CCC(C)C(=O)C(=O)O,[Soluble (in ethanol)]
44,48,C(CC(=O)N)C(=O)C(=O)O,None
45,49,CC(C)C(=O)C(=O)O,None
46,50,C(C(C(C(C(=O)C(=O)O)O)O)O)O,None
47,51,C(CC(=O)O)C(=O)C(=O)O,None
48,52,CC(C(C)O)C(=O)SCCNC(=O)CCNC(=O)C(C(C)(C)COP(=O...,None
49,53,CC(C(=O)C)C(=O)SCCNC(=O)CCNC(=O)C(C(C)(C)COP(=...,None

In [ ]:
### Sorting the data with solubility and dicarding the null
df_n = df_new.loc[df_new['Solubility'].notnull(), ['SMILES','Solubility']]
print(len(df_n))

7

In [ ]:
### Making dataframe 
df_n=pd.DataFrame(df_n)

In [ ]:
print(len(df_n))

7

In [ ]:
df_n

,SMILES,Solubility
3,CC(CN)O,"[SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ..."
5,C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl,"[In water, 9.24 mg/L at 25 °C]"
9,C(CCl)Cl,"[In water, 8,600 mg/L at 25 °C]"
11,C1=CC(=C(C=C1Cl)Cl)Cl,[Sparingly soluble in alcohol. Miscible with e...
29,C(C=O)Cl,[Miscible in all proportions with water]
30,C(CCl)O,"[SOL IN ALL PROPORTIONS IN WATER, ALC, ORG SOL..."
43,CCC(C)C(=O)C(=O)O,[Soluble (in ethanol)]

In [ ]:
sol_new=df_n.Solubility

In [ ]:
sol_new

3     [SOL IN ALL PROPORTIONS IN WATER, ALC, ETHER, ...
5                        [In water, 9.24 mg/L at 25 °C]
9                       [In water, 8,600 mg/L at 25 °C]
11    [Sparingly soluble in alcohol. Miscible with e...
29             [Miscible in all proportions with water]
30    [SOL IN ALL PROPORTIONS IN WATER, ALC, ORG SOL...
43                               [Soluble (in ethanol)]
Name: Solubility, dtype: object

In [ ]:
import re
sol1=[]
### Using regular expression module cleaning the data and taking out the data with with unit "mg/mL" in the pubchem ... 
for s in sol_new:
   sol=re.findall(r'(?<![\-\/])(\d+(?:\.?\d+)) *mg\b', s)
   sol1.append(sol) 
print(len(sol1))

TypeError: ignored

In [ ]:
df3=df_n.SMILES

In [ ]:
df3.reset_index(drop=True, inplace=True)

In [ ]:
print(type(df3))

<class 'pandas.core.series.Series'>

In [ ]:
df2 = pd.DataFrame(sol1)
df2.columns =['Solubility_new']
print(len(df2))

953

In [ ]:
df_new = pd.concat([df3,df2], axis=1,ignore_index=True)
df_new

                                                     0     1
0                                              CC(CN)O   100
1            C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl  None
2                                             C(CCl)Cl    10
3                                C1=CC(=C(C=C1Cl)Cl)Cl  None
4                                             C(C=O)Cl   100
..                                                 ...   ...
948                CC(C)NCC(C1=CC=C(C=C1)NS(=O)(=O)C)O  None
949  C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCCC(=O)C4=CC=C...  None
950  CC1CC=CC=CC(C(CC(C(C(C(CC(=O)O1)O)OC)OC2C(C(C(...  None
951                      CC1=CN(C(=O)NC1=O)C2CCC(O2)CO  None
952                            CCCCCCCCCCCCCCCCCC(=O)O    10

[953 rows x 2 columns]

In [ ]:
df_new.columns =['SMILES', 'SOLUBILITY mg/mL']

In [ ]:
df_new

                                                SMILES SOLUBILITY mg/mL
0                                              CC(CN)O              100
1            C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl             None
2                                             C(CCl)Cl               10
3                                C1=CC(=C(C=C1Cl)Cl)Cl             None
4                                             C(C=O)Cl              100
..                                                 ...              ...
948                CC(C)NCC(C1=CC=C(C=C1)NS(=O)(=O)C)O             None
949  C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCCC(=O)C4=CC=C...             None
950  CC1CC=CC=CC(C(CC(C(C(C(CC(=O)O1)O)OC)OC2C(C(C(...             None
951                      CC1=CN(C(=O)NC1=O)C2CCC(O2)CO             None
952                            CCCCCCCCCCCCCCCCCC(=O)O               10

[953 rows x 2 columns]

In [ ]:
### Final data would be having the smiles along with solubility 

df_sol = df_new.loc[df_new['SOLUBILITY mg/mL'].notnull(), ['SMILES','SOLUBILITY mg/mL']]
df_sol

                                                SMILES SOLUBILITY mg/mL
0                                              CC(CN)O              100
2                                             C(CCl)Cl               10
4                                             C(C=O)Cl              100
5                                              C(CCl)O              100
6                                    CCC(C)C(=O)C(=O)O            915.5
..                                                 ...              ...
937  COC1=C(C=CC(=C1)C2C(OC3=C(O2)C=C(C=C3)C4C(C(=O...            77.36
939                                        [Na+].[Cl-]              100
940                                         [F-].[Na+]               50
943                                         C(C(=O)O)I              100
952                            CCCCCCCCCCCCCCCCCC(=O)O               10

[164 rows x 2 columns]

In [ ]:
df_sol.to_csv('/content/drive/MyDrive/pubchem_1_5000.csv')

In [ ]:
import pandas as pd
df =pd.read_csv('/content/drive/MyDrive/pubchem_1_5000.csv')

In [ ]:
df.head()

   Unnamed: 0             SMILES  SOLUBILITY mg/mL
0           0            CC(CN)O             100.0
1           2           C(CCl)Cl              10.0
2           4           C(C=O)Cl             100.0
3           5            C(CCl)O             100.0
4           6  CCC(C)C(=O)C(=O)O             915.5